SUPER_CONFIG_PATH: ./configs/r50_deformable_detr_motip_oceanfish.yaml

SEED: 42
DATASET_SPLITS: [fold2/train]
INFERENCE_SPLIT: fold2/val
SCARCITY_FRAMES: 100

EXP_NAME: p2_fold2_s100
EXP_GROUP: p2_kfold
